language: php

php:
    -   '5.6'
    -   '7'

before_install :
    -   sudo apt-get install -y php5-mysql
    -   composer self-update

before_script :
    -   composer install

script : 
    -   phpunit
